---
- name: Install zsh
  become: yes
  ansible.builtin.apt:
    state: present
    update_cache: true
    pkg:
    - zsh
    
- name: Install powershell
  ansible.builtin.git:
    repo: 'https://github.com/romkatv/powerlevel10k'
    dest: ~/opt/powerlevel10k
    clone: yes