- name: Install cromwell
  gather_facts: No
  become: yes
  hosts: "{{ ansible_limit | default(omit) }}"

  tasks:
    - name: Create cromwell user
      ansible.builtin.user:
        name: cromwell
        groups: docker,adm
        state: present

    - name: Create cromwell directory
      ansible.builtin.file:
        path: /opt/cromwell
        owner: cromwell
        group: cromwell
        state: directory
        mode: '0755'

    - name: Download cromwell
      ansible.builtin.get_url:
        url: https://github.com/broadinstitute/cromwell/releases/download/69/cromwell-69.jar
        dest: /opt/cromwell
        owner: cromwell
        group: cromwell

    - name: Symlink cromwell jar
      ansible.builtin.file:
        src: /opt/cromwell/cromwell-69.jar
        dest: /opt/cromwell/cromwell.jar
        owner: cromwell
        group: cromwell
        state: link

    - name: Copy cromwell running script
      ansible.builtin.copy:
        src: cromwell.sh 
        dest: /opt/cromwell/cromwell.sh
        owner: cromwell
        group: cromwell
        mode: '0755'

    - name: Symlink cromwell script
      ansible.builtin.file:
        src: /opt/cromwell/cromwell.sh
        dest: /usr/bin/cromwell
        state: link

    - name: Copy cromwell config
      template:
        src: cromwell.cfg.j2
        dest: /opt/cromwell/cromwell.cfg
        owner: cromwell
        group: cromwell
        mode: '0644'

    - name: Setup systemd cromwell service
      ansible.builtin.copy:
        src: cromwell.service
        dest: /etc/systemd/system/cromwell.service
        mode: '0644'
