---
- name: Install pip
  become: yes
  apt:
    state: present
    update_cache: true
    pkg:
      - python3-pip
- name: Install powerline fonts
  become: yes
  apt:
    state: present
    update_cache: true
    pkg:
      - fonts-powerline
- name: Install powerline
  become: yes
  pip:
    name: powerline-status
- name: Create .config directory
  file:
    path: .config
    state: directory
    mode: '0755'
- name: Copy powerline .config
  copy:
    src: powerline
    dest: .config/ 
- name: Set prompt color
  template:
    src: colors.json.j2
    dest: .config/powerline/colors.json
- name: Copy bashrc
  copy:
    src: "{{ item }}"
    dest: .
  with_fileglob:
    - .bash*
  
