---
- hosts: master
  vars: 
    certbot_generate_certificates: true
    certbot_register_email: piechota.marcin@gmail.com
    certbot_certificate_domains:
      - traefik.labpgx.com
      - apache.labpgx.com
  roles:
    - apache
