---
- hosts: prometheus
  roles:
  - cloudalchemy.prometheus
  - cloudalchemy.grafana
  vars:
    prometheus_targets:
      node:
      - targets:
        - {{ node }}
        labels:
          env: ippas
    grafana_datasources:
      - name: prometheus
        type: prometheus
        access: proxy
        url: 'http://localhost:9090'
        basicAuth: false
    grafana_dashboards:
      - dashboard_id: 111
        revision_id: 1
        datasource: prometheus
    grafana_security:
      admin_user: {{ grafana_user }}
      admin_password: {{ grafana_password }}
